---
title: "Projects"
---

In the Summer 2020, I took an Intro GIS course using R language and software. I drafted code, completed data science projects, and improved my geospatial data skills. This is a collection of my work, and it will not cover anything outside of the Introduction course. 

## [Building a project website (R)](https://github.com/Hindstein/GEOG176A/blob/master/index.html)
 
 - This assignment focused on building a static user site with Github Pages
 - Includes a github repository for access to all the code involved
 - The quality of work is a big step-up from my previous experience
 - Completed using *RStudio* and *R* language
 - Familiarizes *RStudio* and *Github* transparency
 
 
## [COVID-19 Pandemic (R)](https://hindstein.github.io/geog-176A-labs/lab-02-ianhinds.html)
 
 - This lab breaks down NY Times data on the COVID-19 Pandemic
 - It includes the use of ggplot, and data manipulation to visualize the effects of COVID on different populations
 - The results expose natural spread, and the effects of preventative methods (mask, Social Distancing, etc.)
 
 
## [Distances and Projections (R)](https://hindstein.github.io/geog-176A-labs/lab-03-ianhinds.html)
 
 - This journal uses *simple features*, *USAboundaries*, *rnaturalearthdata* to measure border distances and project border zones
 - Data Wrangling
 - Identifying distances
 - Applying boundary lines and data to study regions
 - Quantifying border zones
 - Mapping border zones
 
*****